#**SVM**
Aplicando com Python

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [ ]:
base = pd.read_csv('fetal_health.csv')

In [ ]:
X = base.drop(columns=['fetal_health'])
Y = base['fetal_health']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

#Kernel

O kernel é uma função fundamental no SVM (Support Vector Machine) que define como os dados serão transformados antes de serem classificados. O SVM funciona ao encontrar um hiperplano que separa as classes de dados no espaço de características. No caso de dados linearmente separáveis, um hiperplano simples pode ser suficiente. No entanto, quando os dados não são linearmente separáveis, o SVM usa uma função kernel para transformar os dados em um espaço de maior dimensão onde a separação linear se torna possível.

Imagine que você tem dois grupos de pontos em um gráfico 2D: triângulos (A) e círculos (B). Eles estão bem separados, e você pode traçar uma linha reta entre eles para dividir as classes. O SVM com kernel linear encontra essa linha que melhor separa os dois grupos, garantindo a maior distância possível entre a linha e os pontos mais próximos de cada grupo. Assim, ele pode classificar novos pontos dependendo de qual lado da linha eles caem.

In [ ]:
svm_model = SVC(kernel =  'linear', random_state = 1, C = 1.0)
svm_model.fit(X_train,Y_train)

SVC(kernel='linear', random_state=1)

In [ ]:
Y_pred = svm_model.predict(X_train)
Y_pred

array([1., 2., 1., ..., 1., 1., 1.])

In [ ]:
report = classification_report(Y_train, Y_pred)
print("Relatório de Classificação:\n", report)

Relatório de Classificação:
               precision    recall  f1-score   support

         1.0       0.92      0.96      0.94      1322
         2.0       0.68      0.52      0.59       231
         3.0       0.83      0.82      0.82       147

    accuracy                           0.89      1700
   macro avg       0.81      0.77      0.79      1700
weighted avg       0.88      0.89      0.88      1700



In [ ]:
accuracy = accuracy_score(Y_train, Y_pred)
print("Acurácia:", accuracy)

Acurácia: 0.888235294117647


# Melhorando os parâmetros:



#Kernel = Poly

Quando você utiliza kernel='poly' no modelo SVM, está escolhendo o kernel polinomial. Esse kernel transforma os dados originais em um espaço de características de maior dimensão usando uma função polinomial.

O kernel polinomial transforma os dados originais em um espaço de características de maior dimensão. Por exemplo, se você tem duas variáveis de entrada (x1 e x2), o kernel polinomial pode gerar termos como x1
∧
 2, x2
∧
 2, x1∗x2, criando uma representação mais complexa dos dados.

O kernel polinomial permite ao SVM operar como se tivesse criado novas variáveis (ou características) no espaço de maior dimensão, possibilitando a separação de dados que não podem ser separados linearmente no espaço original.

In [ ]:
svm_model_poly = SVC(kernel =  'poly', random_state = 1, C = 1.0)
svm_model_poly.fit(X_train,Y_train)

SVC(kernel='poly', random_state=1)

In [ ]:
Y_pred_poly = svm_model_poly.predict(X_train)
Y_pred_poly

array([1., 2., 1., ..., 1., 1., 1.])

In [ ]:
report = classification_report(Y_train, Y_pred_poly)
print("Relatório de Classificação:\n", report)

Relatório de Classificação:
               precision    recall  f1-score   support

         1.0       0.90      0.96      0.93      1322
         2.0       0.67      0.45      0.54       231
         3.0       0.79      0.72      0.75       147

    accuracy                           0.87      1700
   macro avg       0.79      0.71      0.74      1700
weighted avg       0.86      0.87      0.86      1700



In [ ]:
accuracy = accuracy_score(Y_train, Y_pred_poly)
print("Acurácia:", accuracy)

Acurácia: 0.8735294117647059


#Kernel = rbf

Quando você utiliza kernel='rbf' no modelo SVM, está escolhendo o kernel RBF (Radial Basis Function), também conhecido como kernel gaussiano. Esse kernel é um dos mais poderosos e flexíveis, especialmente para dados que não são linearmente separáveis.

O kernel='rbf' transforma os dados para um espaço de características de infinita dimensão, permitindo ao SVM encontrar limites de decisão altamente complexos e curvos, que são adequados para dados com padrões não lineares. É uma escolha popular para problemas difíceis de classificação onde os padrões entre as classes são complexos.

In [ ]:
svm_model_rbf = SVC(kernel =  'rbf', random_state = 1, C = 1.0)
svm_model_rbf.fit(X_train,Y_train)

SVC(random_state=1)

In [ ]:
Y_pred_rbf = svm_model_rbf.predict(X_train)
Y_pred_rbf

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
report = classification_report(Y_train, Y_pred_rbf)
print("Relatório de Classificação:\n", report)

Relatório de Classificação:
               precision    recall  f1-score   support

         1.0       0.89      0.97      0.93      1322
         2.0       0.57      0.39      0.46       231
         3.0       0.88      0.62      0.73       147

    accuracy                           0.86      1700
   macro avg       0.78      0.66      0.70      1700
weighted avg       0.85      0.86      0.85      1700



In [ ]:
accuracy = accuracy_score(Y_train, Y_pred_rbf)
print("Acurácia:", accuracy)

Acurácia: 0.86
